// apps/web/src/components/game/GameBottomBar.tsx
/**
 * GameBottomBar - Mobile bottom navigation bar
 * Ported from legacy/hwe/ts/components/GameBottomBar.vue
 * Only visible on mobile (d-sm-block d-lg-none)
 */

"use client";

import { useState, useRef, useEffect } from "react";

interface MenuItem {
  name: string;
  href?: string;
  onClick?: () => void;
}

interface MenuCategory {
  title: string;
  items: MenuItem[];
}

interface GlobalInfo {
  year: number;
  month: number;
}

interface GeneralInfo {
  permission: number;
  officerLevel: number;
}

interface FrontInfo {
  global: GlobalInfo;
  general: GeneralInfo;
  nation: {
    level: number;
  };
}

interface GlobalMenuItem {
  name: string;
  href?: string;
}

interface GameBottomBarProps {
  frontInfo: FrontInfo;
  globalMenu: GlobalMenuItem[];
  onRefresh: () => void;
}

/**
 * Scroll to a selector
 */
function scrollToSelector(selector: string): void {
  const element = document.querySelector(selector);
  if (element) {
    element.scrollIntoView({ behavior: "smooth", block: "start" });
  }
}

/**
 * Navigate to lobby
 */
function moveLobby(): void {
  window.location.replace("../");
}

export function GameBottomBar({ frontInfo, globalMenu, onRefresh }: GameBottomBarProps) {
  const [openDropdown, setOpenDropdown] = useState<string | null>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Close dropdown when clicking outside
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setOpenDropdown(null);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const showSecret = frontInfo.general.permission >= 1 || frontInfo.general.officerLevel >= 2;

  // Quick navigation items
  const quickNavItems: MenuCategory[] = [
    {
      title: "국가 정보",
      items: [
        { name: "방침", onClick: () => scrollToSelector(".nationNotice") },
        { name: "명령", onClick: () => scrollToSelector("#reservedCommandPanel") },
        { name: "국가", onClick: () => scrollToSelector(".nationInfo") },
        { name: "장수", onClick: () => scrollToSelector(".generalInfo") },
        { name: "도시", onClick: () => scrollToSelector(".cityInfo") },
      ],
    },
    {
      title: "동향 정보",
      items: [
        { name: "지도", onClick: () => scrollToSelector(".mapView") },
        { name: "동향", onClick: () => scrollToSelector(".PublicRecord") },
        { name: "개인", onClick: () => scrollToSelector(".GeneralLog") },
        { name: "정세", onClick: () => scrollToSelector(".WorldHistory") },
      ],
    },
    {
      title: "메시지",
      items: [
        { name: "전체", onClick: () => scrollToSelector(".PublicTalk > .stickyAnchor") },
        { name: "국가", onClick: () => scrollToSelector(".NationalTalk > .stickyAnchor") },
        { name: "개인", onClick: () => scrollToSelector(".PrivateTalk > .stickyAnchor") },
        { name: "외교", onClick: () => scrollToSelector(".DiplomacyTalk > .stickyAnchor") },
      ],
    },
  ];

  // Nation menu items based on permission level
  const nationMenuItems: MenuItem[] = [
    { name: "세력 장수", href: "/nation/generals" },
    { name: "내무부", href: "/nation/finance" },
  ];

  if (showSecret) {
    nationMenuItems.push({ name: "사령부", href: "/chief" }, { name: "부대 편성", href: "/troop" });
  }

  return (
    <nav className="gameBottomBar lg:hidden fixed bottom-0 left-0 right-0 bg-zinc-900 border-t border-zinc-700 z-50">
      <style jsx>{`
        .gameBottomBar {
          box-shadow: 0 -1px 0 #1f2937;
        }

        .dropdown-menu {
          max-height: calc(100vh - 50px);
          overflow-y: auto;
        }

        .dropdown-menu li {
          font-size: 16px;
        }

        .nav-btn {
          text-align: center;
          width: 100px;
          font-size: 14px;
          padding: 8px 12px;
        }

        @media (min-width: 500px) {
          .nav-btn {
            width: 125px;
            font-size: 16px;
          }
        }
      `}</style>

      <div className="flex justify-center items-center py-2 gap-1" ref={dropdownRef}>
        {/* Global Menu */}
        <div className="relative">
          <button
            className="nav-btn bg-zinc-700 hover:bg-zinc-600 text-white rounded transition-colors"
            onClick={() => setOpenDropdown(openDropdown === "global" ? null : "global")}
          >
            외부 메뉴 ▲
          </button>
          {openDropdown === "global" && (
            <div className="dropdown-menu absolute bottom-full left-0 mb-1 bg-zinc-800 border border-zinc-600 rounded shadow-lg min-w-[200px]">
              <div className="grid grid-cols-3 gap-1 p-2">
                {globalMenu.map((item, idx) => (
                  <a
                    key={idx}
                    href={item.href}
                    className="text-white hover:bg-zinc-700 px-2 py-1 text-sm rounded text-center"
                  >
                    {item.name}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Nation Menu */}
        <div className="relative">
          <button
            className="nav-btn bg-sammo-nation hover:opacity-80 text-white rounded transition-colors"
            onClick={() => setOpenDropdown(openDropdown === "nation" ? null : "nation")}
          >
            국가 메뉴 ▲
          </button>
          {openDropdown === "nation" && (
            <div className="dropdown-menu absolute bottom-full left-0 mb-1 bg-zinc-800 border border-zinc-600 rounded shadow-lg min-w-[200px]">
              <div className="grid grid-cols-3 gap-1 p-2">
                {nationMenuItems.map((item, idx) => (
                  <a
                    key={idx}
                    href={item.href}
                    className="text-white hover:bg-zinc-700 px-2 py-1 text-sm rounded text-center"
                  >
                    {item.name}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Quick Navigation */}
        <div className="relative">
          <button
            className="nav-btn bg-zinc-800 hover:bg-zinc-700 text-white rounded transition-colors"
            onClick={() => setOpenDropdown(openDropdown === "quick" ? null : "quick")}
          >
            빠른 이동 ▲
          </button>
          {openDropdown === "quick" && (
            <div className="dropdown-menu absolute bottom-full right-0 mb-1 bg-zinc-800 border border-zinc-600 rounded shadow-lg min-w-[300px]">
              <div className="p-2">
                {quickNavItems.map((category, catIdx) => (
                  <div key={catIdx} className="mb-2">
                    <div className="text-zinc-400 text-xs px-2 py-1">{category.title}</div>
                    <hr className="border-zinc-600 my-1" />
                    <div className="grid grid-cols-3 gap-1">
                      {category.items.map((item, itemIdx) => (
                        <button
                          key={itemIdx}
                          onClick={() => {
                            item.onClick?.();
                            setOpenDropdown(null);
                          }}
                          className="text-white hover:bg-zinc-700 px-2 py-1 text-sm rounded text-center"
                        >
                          {item.name}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
                <hr className="border-zinc-600 my-2" />
                <button
                  onClick={() => {
                    moveLobby();
                    setOpenDropdown(null);
                  }}
                  className="w-full bg-zinc-700 hover:bg-zinc-600 text-white px-2 py-2 text-sm rounded"
                >
                  로비로
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Refresh Button */}
        <button
          className="nav-btn bg-zinc-700 hover:bg-zinc-600 text-white rounded transition-colors"
          onClick={onRefresh}
        >
          갱신
        </button>
      </div>
    </nav>
  );
}

// legacy/hwe/ts/components/GameBottomBar.vue
<template>
  <nav class="gameBottomBar navbar-expand navbar-dark bg-dark d-sm-block d-lg-none p-0">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto mx-auto">
        <li class="nav-item dropup">
          <div
            id="navbarGlobal"
            class="dropdown-toggle text-white btn btn-sammo-base2"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            외부 메뉴
          </div>
          <GlobalMenuBar
            id="navbarGlobalItems"
            aria-labelledby="navbarGlobal"
            :globalInfo="globalInfo"
            :modelValue="globalMenu"
            :columns="3"
          />
        </li>
        <li class="nav-item dropup">
          <div
            id="navbarNation"
            class="dropdown-toggle btn btn-sammo-nation controlBar"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            국가 메뉴
          </div>
          <MainControlDropdown
            id="navbarNationItems"
            aria-labelledby="navbarNation"
            :showSecret="showSecret"
            :permission="frontInfo.general.permission"
            :myLevel="frontInfo.general.officerLevel"
            :nationLevel="nationInfo.level"
          />
        </li>
        <li class="nav-item dropup">
          <div
            id="navbarQuick"
            class="dropdown-toggle text-white btn btn-dark"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            빠른 이동
          </div>
          <ul id="navbarQuickItems" class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item disabled">국가 정보</a></li>
            <hr class="dropdown-divider" />
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.nationNotice')">방침</button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('#reservedCommandPanel')">
                명령
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.nationInfo')">국가</button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.generalInfo')">장수</button>
            </li>
            <li><button type="button" class="dropdown-item" @click="scrollToSelector('.cityInfo')">도시</button></li>
            <li><a class="dropdown-item disabled">동향 정보</a></li>
            <hr class="dropdown-divider" />
            <li><button type="button" class="dropdown-item" @click="scrollToSelector('.mapView')">지도</button></li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.PublicRecord')">동향</button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.GeneralLog')">개인</button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.WorldHistory')">정세</button>
            </li>
            <li><span>&nbsp;</span></li>
            <li><a class="dropdown-item disabled">메시지</a></li>
            <hr class="dropdown-divider" />
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.PublicTalk > .stickyAnchor')">
                전체
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.NationalTalk > .stickyAnchor')">
                국가
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.PrivateTalk > .stickyAnchor')">
                개인
              </button>
            </li>
            <li>
              <button type="button" class="dropdown-item" @click="scrollToSelector('.DiplomacyTalk > .stickyAnchor')">
                외교
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-sammo-base2" @click="moveLobby">로비로</button>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="refreshPage btn btn-sammo-base2 text-white" role="button" @click="emit('refresh')">갱신</a>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script setup lang="ts">
import type { GetFrontInfoResponse, GetMenuResponse } from "@/defs/API/Global";
import { scrollToSelector } from "@/util/scrollToSelector";
import { toRefs, watch, ref, computed } from "vue";
import GlobalMenuBar from "./GlobalMenuDropdown.vue";
import MainControlDropdown from "./MainControlDropdown.vue";

//FIXME: scrollToSelector

const props = defineProps<{
  frontInfo: GetFrontInfoResponse;
  globalMenu: GetMenuResponse["menu"];
}>();

const emit = defineEmits<{
  (event: "refresh"): void;
}>();

const { frontInfo, globalMenu } = toRefs(props);

const globalInfo = ref(frontInfo.value.global);
watch(frontInfo, (frontInfo) => {
  globalInfo.value = frontInfo.global;
});

const nationInfo = ref(frontInfo.value.nation);
watch(frontInfo, (frontInfo) => {
  nationInfo.value = frontInfo.nation;
});

function moveLobby() {
  location.replace("../");
}

const showSecret = computed(() => {
  if (!frontInfo.value) {
    return false;
  }
  if (frontInfo.value.general.permission >= 1) {
    return true;
  }
  if (frontInfo.value.general.officerLevel >= 2) {
    return true;
  }
  return false;
});
</script>

<style lang="scss" scoped>
@import "@scss/common/break_500px.scss";
@import "@scss/common/base.scss";

@include media-500px {
  .gameBottomBar {
    .nav-item ul.dropdown-menu {
      max-height: calc(100vh - 50px);
      overflow-y: auto;

      li {
        font-size: 16px;
      }
    }

    .nav-item > .btn {
      text-align: center;
      width: 125px;
      font-size: 16px;
    }

    box-shadow: 0 -1px 0 $dark;
    border-left: none !important;
    border-right: none !important;
  }

  #navbarNationItems {
    columns: 3;
  }

  #navbarQuickItems {
    columns: 3;
  }
}
</style>
