// apps/web/src/components/game/MessagePlate.tsx
"use client";

import { useMemo } from "react";

// ============================================================================
// Types
// ============================================================================

export type MsgType = "private" | "public" | "national" | "diplomacy";

export type MsgTarget = {
  id: number;
  name: string;
  nation_id: number;
  nation: string;
  color: string;
  icon: string;
};

export type MsgActionType = "scout" | "noAggression" | "cancelNA" | "stopWar";

export interface MsgItem {
  id: number;
  msgType: MsgType;
  src: MsgTarget;
  dest?: MsgTarget;
  text: string;
  option: {
    action?: MsgActionType;
    invalid?: boolean;
    deletable?: boolean;
    overwrite?: number[];
    hide?: boolean;
    silence?: boolean;
    delete?: number;
  };
  time: string;
}

// ============================================================================
// Utility Functions
// ============================================================================

function isBrightColor(color: string): boolean {
  // Convert hex to RGB and calculate luminance
  const hex = color.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.5;
}

function getIconPath(icon: string | undefined): string {
  if (!icon) return "/icons/default.jpg";
  return icon;
}

// Simple linkify - convert URLs to anchor tags
function linkifyText(text: string): string {
  const urlPattern = /(https?:\/\/[^\s]+)/g;
  return text.replace(
    urlPattern,
    '<a href="$1" target="_blank" rel="noopener noreferrer" class="text-blue-400 hover:underline">$1</a>'
  );
}

// ============================================================================
// Component Props
// ============================================================================

interface MessagePlateProps {
  message: MsgItem;
  generalID: number;
  generalName: string;
  nationID: number;
  permissionLevel: number;
  deleted?: boolean;
  onSetTarget?: (type: MsgType, target: MsgTarget) => void;
  onDelete?: (msgId: number) => void;
  onAccept?: (msgId: number) => void;
  onDecline?: (msgId: number) => void;
  onRequestRefresh?: () => void;
}

// ============================================================================
// Component
// ============================================================================

export function MessagePlate({
  message,
  generalID,
  generalName,
  nationID,
  permissionLevel,
  deleted = false,
  onSetTarget,
  onDelete,
  onAccept,
  onDecline,
}: MessagePlateProps) {
  const msg = message;
  const src = msg.src;
  const dest = msg.dest ?? {
    id: 0,
    name: "",
    nation: "재야",
    nation_id: 0,
    color: "#000000",
    icon: "",
  };

  const srcColorType = isBrightColor(src.color) ? "bright" : "dark";
  const destColorType = isBrightColor(dest.color) ? "bright" : "dark";

  const isValidMsg = useMemo(() => {
    if (deleted) return false;
    if (msg.option.invalid) return false;
    return true;
  }, [deleted, msg.option.invalid]);

  const deletable = useMemo(() => {
    if (deleted) return false;
    if (msg.option.action) return false;
    if (msg.src.id !== generalID) return false;
    if (msg.option.invalid) return false;
    if (!(msg.option.deletable ?? true)) return false;
    // Note: Time-based deletability check would need to be implemented with useEffect
    return true;
  }, [deleted, msg, generalID]);

  const allowButton = useMemo(() => {
    if (msg.msgType !== "diplomacy") return true;
    if (permissionLevel >= 4) return true;
    return false;
  }, [msg.msgType, permissionLevel]);

  const nationType = useMemo((): "local" | "src" | "dest" => {
    if (msg.src.nation_id === msg.dest?.nation_id) return "local";
    if (msg.src.nation_id === nationID) return "src";
    return "dest";
  }, [msg.src.nation_id, msg.dest?.nation_id, nationID]);

  // Background color based on message type - now with gradients for depth
  const bgColorClass = useMemo(() => {
    const base: Record<MsgType, string> = {
      private: "bg-gradient-to-br from-[#6d2e2a] to-[#4d0e0a]",
      public: "bg-gradient-to-br from-[#1e2c75] to-[#0a1245]",
      national: "bg-gradient-to-br from-[#10683c] to-[#00481c]",
      diplomacy: "bg-gradient-to-br from-[#10683c] to-[#00481c]",
    };

    if (
      (msg.msgType === "private" || msg.msgType === "national" || msg.msgType === "diplomacy") &&
      nationType === "dest"
    ) {
      if (msg.msgType === "private") return "bg-gradient-to-br from-[#6d562a] to-[#4d360a]";
      return "bg-gradient-to-br from-[#805625] to-[#603605]";
    }
    if ((msg.msgType === "national" || msg.msgType === "diplomacy") && nationType === "src") {
      return "bg-gradient-to-br from-[#80254b] to-[#60052b]";
    }
    return base[msg.msgType];
  }, [msg.msgType, nationType]);

  const handleSetTarget = (target: MsgTarget) => {
    onSetTarget?.(msg.msgType, target);
  };

  const handleDelete = () => {
    if (confirm("삭제하시겠습니까?")) {
      onDelete?.(msg.id);
    }
  };

  const handleAccept = () => {
    if (confirm("수락하시겠습니까?")) {
      onAccept?.(msg.id);
    }
  };

  const handleDecline = () => {
    if (confirm("거절하시겠습니까?")) {
      onDecline?.(msg.id);
    }
  };

  // Render header based on message type
  const renderHeader = () => {
    const TargetBadge = ({
      target,
      colorType,
      clickable = false,
      children,
    }: {
      target: MsgTarget;
      colorType: "bright" | "dark";
      clickable?: boolean;
      children: React.ReactNode;
    }) => (
      <span
        role={clickable ? "button" : undefined}
        className={`inline-block mx-0.5 px-1.5 py-0.5 rounded-md font-medium transition-all duration-150 ${
          colorType === "bright" ? "text-black/90" : "text-white"
        } ${clickable ? "cursor-pointer hover:brightness-110 hover:scale-[1.02] active:scale-[0.98]" : ""}`}
        style={{
          backgroundColor: target.color,
          boxShadow: "0 1px 2px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.15)",
          textShadow: colorType === "dark" ? "0 1px 1px rgba(0,0,0,0.3)" : "none",
        }}
        onClick={clickable ? () => handleSetTarget(target) : undefined}
      >
        {children}
      </span>
    );

    if (msg.msgType === "private") {
      if (src.name === generalName) {
        return (
          <>
            <TargetBadge target={src} colorType={srcColorType}>
              나
            </TargetBadge>
            <span className="mx-1">▶</span>
            <TargetBadge target={dest} colorType={destColorType} clickable>
              {dest.name}:{dest.nation} | ↩
            </TargetBadge>
          </>
        );
      }
      return (
        <>
          <TargetBadge target={src} colorType={srcColorType} clickable>
            {src.name}:{src.nation} | ↩
          </TargetBadge>
          <span className="mx-1">▶</span>
          <TargetBadge target={dest} colorType={destColorType}>
            나
          </TargetBadge>
        </>
      );
    }

    if (msg.msgType === "national" && src.nation_id === dest.nation_id) {
      return (
        <TargetBadge target={src} colorType={srcColorType}>
          {src.name}
        </TargetBadge>
      );
    }

    if ((msg.msgType === "national" || msg.msgType === "diplomacy") && permissionLevel >= 4) {
      if (src.nation_id === nationID) {
        return (
          <>
            <TargetBadge target={src} colorType={srcColorType}>
              {src.name}
            </TargetBadge>
            <span className="mx-1">▶</span>
            <TargetBadge target={dest} colorType={destColorType} clickable>
              {dest.nation} | ↩
            </TargetBadge>
          </>
        );
      }
      return (
        <TargetBadge target={src} colorType={srcColorType} clickable>
          {src.name}:{src.nation} | ↩
        </TargetBadge>
      );
    }

    if (msg.msgType === "national" || msg.msgType === "diplomacy") {
      if (src.nation_id === nationID) {
        return (
          <>
            <TargetBadge target={src} colorType={srcColorType}>
              {src.name}
            </TargetBadge>
            <span className="mx-1">▶</span>
            <TargetBadge target={dest} colorType={destColorType}>
              {dest.nation}
            </TargetBadge>
          </>
        );
      }
      return (
        <TargetBadge target={src} colorType={srcColorType}>
          {src.name}:{src.nation}
        </TargetBadge>
      );
    }

    // public message
    if (src.id !== generalID) {
      return (
        <TargetBadge target={src} colorType={srcColorType} clickable>
          {src.name}:{src.nation} | ↩
        </TargetBadge>
      );
    }
    return (
      <TargetBadge target={src} colorType={srcColorType}>
        {src.name}
      </TargetBadge>
    );
  };

  return (
    <div
      id={`msg_${msg.id}`}
      className={`grid grid-cols-[64px_1fr] border-b border-gray-600/50 min-h-[64px] text-xs text-white break-all transition-colors ${bgColorClass}`}
      data-id={msg.id}
    >
      {/* Icon */}
      <div className="w-16 h-16 border-r border-gray-600/50 flex-shrink-0 overflow-hidden">
        <img
          src={getIconPath(src.icon)}
          alt={src.name}
          width={64}
          height={64}
          className="object-cover"
        />
      </div>

      {/* Body */}
      <div className="py-1 px-2 flex flex-col">
        {/* Header */}
        <div className="font-bold mb-1 relative">
          {deletable && (
            <button
              type="button"
              className="absolute right-0 top-0 px-1.5 py-0.5 text-[8px] border border-yellow-500/70 text-yellow-500 rounded-md hover:bg-yellow-500 hover:text-black transition-colors"
              onClick={handleDelete}
            >
              ❌
            </button>
          )}
          {renderHeader()}
          <span className="text-[0.75em] font-normal ml-1 text-gray-300">&lt;{msg.time}&gt;</span>
        </div>

        {/* Content */}
        <div
          className={`ml-2 mr-1 ${isValidMsg ? "" : "text-white/50"}`}
          dangerouslySetInnerHTML={{
            __html: isValidMsg ? linkifyText(msg.text) : "삭제된 메시지입니다",
          }}
        />

        {/* Action buttons */}
        {msg.option.action && (
          <div className="text-right mt-1.5 mr-1 space-x-2">
            <button
              type="button"
              disabled={!allowButton}
              onClick={handleAccept}
              className="px-2.5 py-1 bg-gradient-to-b from-green-500 to-green-600 text-white rounded-md text-xs font-medium shadow-sm hover:from-green-400 hover:to-green-500 active:scale-[0.98] transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:from-green-500 disabled:hover:to-green-600"
            >
              수락
            </button>
            <button
              type="button"
              disabled={!allowButton}
              onClick={handleDecline}
              className="px-2.5 py-1 bg-gradient-to-b from-red-500 to-red-600 text-white rounded-md text-xs font-medium shadow-sm hover:from-red-400 hover:to-red-500 active:scale-[0.98] transition-all disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:from-red-500 disabled:hover:to-red-600"
            >
              거절
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// legacy/hwe/ts/components/MessagePlate.vue
<template>
  <div
    :id="`msg_${msg.id}`"
    :class="['msg_plate', `msg_plate_${msg.msgType}`, `msg_plate_${nationType}`]"
    :data-id="msg.id"
  >
    <div class="msg_icon">
      <img v-if="src.icon" class="generalIcon" width="64" height="64" :src="encodeURI(src.icon)" />
      <img v-else class="generalIcon" width="64" height="64" :src="encodeURI(defaultIcon)" />
    </div>
    <div class="msg_body">
      <div class="msg_header">
        <template v-if="deletable">
          <button
            type="button"
            class="btn btn btn-outline-warning btn-sm btn-delete-msg"
            style="float: right"
            @click="tryDelete"
          >
            ❌
          </button>
        </template>

        <template v-if="msg.msgType == 'private'">
          <template v-if="src.name == generalName">
            <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }">나</span
            ><span class="msg_from_to">▶</span
            ><span
              role="button"
              :class="`msg_target msg_${destColorType}`"
              :style="{ backgroundColor: dest.color }"
              @click="emit('setTarget', msg.msgType, dest)"
              >{{ dest.name }}:{{ dest.nation }} | <i class="bi bi-reply-fill"
            /></span>
          </template>
          <template v-else>
            <span
              role="button"
              :class="`msg_target msg_${srcColorType}`"
              :style="{ backgroundColor: src.color }"
              @click="emit('setTarget', msg.msgType, src)"
              >{{ src.name }}:{{ src.nation }} | <i class="bi bi-reply-fill" /></span
            ><span class="msg_from_to">▶</span
            ><span :class="`msg_target msg_${destColorType}`" :style="{ backgroundColor: dest.color }">나</span>
          </template>
        </template>
        <template v-else-if="msg.msgType == 'national' && src.nation_id === dest.nation_id">
          <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }">{{ src.name }}</span>
        </template>
        <template v-else-if="(msg.msgType == 'national' || msg.msgType == 'diplomacy') && permissionLevel >= 4">
          <template v-if="src.nation_id == nationID">
            <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }">{{ src.name }}</span
            ><span class="msg_from_to">▶</span
            ><span
              role="button"
              :class="`msg_target msg_${destColorType}`"
              :style="{ backgroundColor: dest.color }"
              @click="emit('setTarget', msg.msgType, dest)"
              >{{ dest.nation }} | <i class="bi bi-reply-fill"
            /></span>
          </template>
          <template v-else>
            <span
              role="button"
              :class="`msg_target msg_${srcColorType}`"
              :style="{ backgroundColor: src.color }"
              @click="emit('setTarget', msg.msgType, src)"
              >{{ src.name }}:{{ src.nation }} | <i class="bi bi-reply-fill" /></span
            ><span class="msg_from_to"></span>
          </template>
        </template>
        <template v-else-if="msg.msgType == 'national' || msg.msgType == 'diplomacy'">
          <template v-if="src.nation_id == nationID">
            <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }">{{ src.name }}</span
            ><span class="msg_from_to">▶</span
            ><span :class="`msg_target msg_${destColorType}`" :style="{ backgroundColor: dest.color }">{{
              dest.nation
            }}</span>
          </template>
          <template v-else>
            <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }"
              >{{ src.name }}:{{ src.nation }}</span
            ><span class="msg_from_to"></span>
          </template>
        </template>
        <template v-else-if="src.id != props.generalID">
          <span
            role="button"
            :class="`msg_target msg_${srcColorType}`"
            :style="{ backgroundColor: src.color }"
            @click="emit('setTarget', msg.msgType, src)"
            >{{ src.name }}:{{ src.nation }} | <i class="bi bi-reply-fill"
          /></span>
        </template>
        <template v-else>
          <span :class="`msg_target msg_${srcColorType}`" :style="{ backgroundColor: src.color }">{{ src.name }}</span>
        </template>
        <span class="msg_time">&lt;{{ msg.time }}&gt;</span>
      </div>
      <!-- eslint-disable-next-line vue/no-v-html vue/max-attributes-per-line -->
      <div
        :class="['msg_content', isValidMsg ? 'msg_valid' : 'msg_invalid']"
        v-html="isValidMsg ? linkifyStr(msg.text) : '삭제된 메시지입니다'"
      ></div>
      <div v-if="msg.option.action" class="msg_prompt">
        <button
          type="button"
          class="prompt_yes btn_prompt"
          :disabled="allowButton ? undefined : true"
          @click="tryAccept"
        >
          수락
        </button>
        <button
          type="button"
          class="prompt_no btn_prompt"
          :disabled="allowButton ? undefined : true"
          @click="tryDecline"
        >
          거절
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { MsgItem, MsgTarget, MsgType } from "@/defs/API/Message";
import { parseTime } from "@/util/parseTime";
import { differenceInMilliseconds, addMinutes } from "date-fns/esm";
import { computed, onMounted, ref, toRef, watch, type ComputedRef, type Ref } from "vue";
import linkifyStr from "linkify-string";
import { SammoAPI } from "@/SammoAPI";
import { isError, isString } from "lodash-es";
import { isBrightColor } from "@/util/isBrightColor";

const props = defineProps<{
  modelValue: MsgItem;
  generalID: number;
  generalName: string;
  nationID: number;
  permissionLevel: number;
  deleted?: boolean;
}>();

const emit = defineEmits<{
  (event: "response"): void;
  (event: "setTarget", type: MsgType, target: MsgTarget): void;
  (event: "request-refresh"): void;
}>();

const src: Ref<MsgTarget> = ref(props.modelValue.src);
const dest: Ref<MsgTarget> = ref(props.modelValue.dest ?? props.modelValue.src);
const srcColorType = computed(() => (isBrightColor(src.value.color) ? "bright" : "dark"));
const destColorType = computed(() => (isBrightColor(dest.value.color) ? "bright" : "dark"));

const msg = toRef(props, "modelValue");
const defaultIcon = `${window.pathConfig.sharedIcon}/default.jpg`;

const isValidMsg = ref(true);
const deletable = ref(false);

watch(
  () => props.deleted,
  () => {
    isValidMsg.value = testValidMsg(msg.value);
    deletable.value = testDeletable(msg.value);
  },
);

watch(msg, (msg) => {
  isValidMsg.value = testValidMsg(msg);
  deletable.value = testDeletable(msg);

  src.value = msg.src;
  dest.value = msg.dest ?? {
    id: 0,
    name: "",
    nation: "재야",
    nation_id: 0,
    color: "#000000",
    icon: defaultIcon,
  };
});

const deletableTimer: Ref<number | undefined> = ref();
const allowButton = computed(() => {
  if (msg.value.msgType != "diplomacy") {
    return true;
  }
  if (props.permissionLevel >= 4) {
    return true;
  }
  return false;
});

function testDeletable(msg: MsgItem): boolean {
  if (deletableTimer.value) {
    clearTimeout(deletableTimer.value);
  }

  if (props.deleted) return false;
  if (msg.option.action) return false;
  if (msg.src.id != props.generalID) return false;
  if (msg.option.invalid) return false;
  if (!(msg.option.deletable ?? true)) return false;

  const now = new Date();
  const last5min = addMinutes(parseTime(msg.time), 5);
  const timeDiff = differenceInMilliseconds(last5min, now);

  if (timeDiff <= 0) return false;

  deletableTimer.value = window.setTimeout(() => {
    deletable.value = testDeletable(msg);
  }, timeDiff);

  return true;
}

onMounted(() => {
  isValidMsg.value = testValidMsg(msg.value);
  deletable.value = testDeletable(msg.value);
});

const nationType: ComputedRef<"local" | "src" | "dest"> = computed(() => {
  if (msg.value.src.nation_id === msg.value.dest?.nation_id) {
    return "local";
  }

  if (msg.value.src.nation_id === props.nationID) {
    return "src";
  }
  return "dest";
});

function testValidMsg(msg: MsgItem): boolean {
  if (props.deleted) {
    return false;
  }
  if (msg.option.invalid) {
    return false;
  }

  return true;
}

async function tryDelete() {
  emit("response");
  if (!confirm("삭제하시겠습니까?")) {
    return false;
  }
  try {
    await SammoAPI.Message.DeleteMessage({ msgID: msg.value.id });
  } catch (e) {
    if (isString(e)) {
      alert(e);
    }
    if (isError(e)) {
      alert(e.message);
    }
    console.error(e);
  }
  emit("request-refresh");
}

async function tryAccept() {
  emit("response");
  if (!confirm("수락하시겠습니까?")) {
    return false;
  }
  try {
    await SammoAPI.Message.DecideMessageResponse({ msgID: msg.value.id, response: true });
  } catch (e) {
    if (isString(e)) {
      alert(e);
    }
    if (isError(e)) {
      alert(e.message);
    }
    console.error(e);
  }
  emit("request-refresh");
}

async function tryDecline() {
  emit("response");
  if (!confirm("거절하시겠습니까?")) {
    return false;
  }
  try {
    await SammoAPI.Message.DecideMessageResponse({ msgID: msg.value.id, response: false });
  } catch (e) {
    if (isString(e)) {
      alert(e);
    }
    if (isError(e)) {
      alert(e.message);
    }
    console.error(e);
  }
  emit("request-refresh");
}
</script>

<style lang="scss" scoped>
.msg_plate {
  width: 100%;
  display: grid;
  grid-template-columns: 64px 1fr;
  border-bottom: solid 1px gray;
  min-height: 64px;
  font-size: 12.5px;
  word-break: break-all;
  color: white;
}

.msg_plate_private {
  background-color: #5d1e1a;
}

.msg_plate_private.msg_plate_dest {
  background-color: #5d461a;
}

.msg_plate_public {
  background-color: #141c65;
}

.msg_plate_national,
.msg_plate_diplomacy {
  background-color: #00582c;
}

.msg_plate_national.msg_plate_dest,
.msg_plate_diplomacy.msg_plate_dest {
  background-color: #704615;
}

.msg_plate_national.msg_plate_src,
.msg_plate_diplomacy.msg_plate_src {
  background-color: #70153b;
}

.msg_icon {
  width: 64px;
  height: 64px;
  border-right: solid 1px gray;
}

.msg_time {
  font-size: 0.75em;
  font-weight: normal;
}

.msg_header {
  font-weight: bold;
  margin-bottom: 3px;
  color: white;
  position: relative;
}

.msg_invalid {
  color: rgba(255, 255, 255, 0.5);
}

.msg_content {
  margin-left: 10px;
  margin-right: 5px;
  overflow: hidden;
}

.msg_target {
  margin: 2px 2px 0 2px;
  padding: 2px 3px;
  display: inline-block;
  box-shadow: 2px 2px black;
  border-radius: 3px;
}
.msg_target.msg_bright {
  color: black;
}

.msg_target.msg_dark {
  color: white;
}

.msg_from_to {
  display: inline-block;
}

.msg_prompt {
  text-align: right;
  margin-top: 5px;
  margin-right: 5px;
}
.btn-delete-msg {
  position: absolute;
  right: 0;
  top: 0;
  margin: 2px 2px 0 2px;
  font-size: 8px;
}
</style>
