// legacy/hwe/ts/components/GeneralBasicCard.vue
<template>
  <div class="general-card-basic bg2">
    <div
      class="general-icon"
      :style="{
        backgroundImage: `url('${iconPath}')`,
      }"
    ></div>

    <div
      class="general-name"
      :style="{
        color: isBrightColor(nation.color) ? '#000' : '#fff',
        backgroundColor: nation.color,
      }"
    >
      {{ general.name }} 【
      <template v-if="2 <= general.officerLevel && general.officerLevel <= 4 && general.officer_city">
        {{ formatCityName(general.officer_city, gameConstStore) }}
      </template>
      {{ general.officerLevelText }} | {{ generalTypeCall }} |
      <span :style="{ color: injuryInfo.color }">{{ injuryInfo.text }}</span>
      】 {{ general.turntime.substring(11, 19) }}
    </div>

    <div class="bg1">통솔</div>
    <div>
      <div class="row gx-0">
        <div class="col">
          <span :style="{ color: injuryInfo.color }">{{ calcInjury("leadership", general) }}</span>
          <!-- eslint-disable-next-line vue/no-v-html -->
          <span v-if="general.lbonus > 0" style="color: cyan">+{{ general.lbonus }}</span>
        </div>
        <div class="col align-self-center">
          <SammoBar :height="10" :percent="(general.leadership_exp / statUpThreshold) * 100" />
        </div>
      </div>
    </div>
    <div class="bg1">무력</div>
    <div>
      <div class="row gx-0">
        <div class="col" :style="{ color: injuryInfo.color }">
          {{ calcInjury("strength", general) }}
        </div>
        <div class="col align-self-center">
          <SammoBar :height="10" :percent="(general.strength_exp / statUpThreshold) * 100" />
        </div>
      </div>
    </div>
    <div class="bg1">지력</div>
    <div>
      <div class="row gx-0">
        <div class="col" :style="{ color: injuryInfo.color }">
          {{ calcInjury("intel", general) }}
        </div>
        <div class="col align-self-center">
          <SammoBar :height="10" :percent="(general.intel_exp / statUpThreshold) * 100" />
        </div>
      </div>
    </div>

    <div class="bg1">명마</div>
    <div v-if="!horse.info">{{ horse.name }}</div>
    <div v-else v-b-tooltip.hover="horse.info">{{ horse.name }}</div>

    <div class="bg1">무기</div>
    <div v-if="!weapon.info">{{ weapon.name }}</div>
    <div v-else v-b-tooltip.hover="weapon.info">{{ weapon.name }}</div>

    <div class="bg1">서적</div>
    <div v-if="!book.info">{{ book.name }}</div>
    <div v-else v-b-tooltip.hover="book.info">{{ book.name }}</div>

    <div class="bg1">자금</div>
    <div>{{ general.gold.toLocaleString() }}</div>
    <div class="bg1">군량</div>
    <div>{{ general.rice.toLocaleString() }}</div>
    <div class="bg1">도구</div>
    <div v-if="!item.info">{{ item.name }}</div>
    <div v-else v-b-tooltip.hover="item.info">{{ item.name }}</div>

    <!-- TODO: show_img_level을 고려 -->
    <div
      class="general-crew-type-icon"
      :style="{
        backgroundImage: `url('${imagePath}/crewtype${general.crewtype}.png')`,
      }"
    ></div>

    <div class="bg1">병종</div>
    <div v-if="!crewtype.info">{{ crewtype.name }}</div>
    <div v-else v-b-tooltip.hover="crewtype.info">{{ crewtype.name }}</div>
    <div class="bg1">병사</div>
    <div>{{ general.crew.toLocaleString() }}</div>
    <div class="bg1">성격</div>
    <div v-if="!personal.info">{{ personal.name }}</div>
    <div v-else v-b-tooltip.hover="personal.info">{{ personal.name }}</div>

    <!-- TODO: bonusTrain 같은 개념이 필요 -->
    <div class="bg1">훈련</div>
    <div>{{ general.train }}</div>
    <div class="bg1">사기</div>
    <div>{{ general.atmos }}</div>
    <div class="bg1">특기</div>
    <div>
      <span v-if="!specialDomestic.info"> {{ specialDomestic.name }}</span
      ><span v-else v-b-tooltip.hover="specialDomestic.info"> {{ specialDomestic.name }}</span>
      /
      <span v-if="!specialWar.info"> {{ specialWar.name }}</span
      ><span v-else v-b-tooltip.hover="specialWar.info"> {{ specialWar.name }}</span>
    </div>

    <div class="bg1">Lv</div>
    <!-- TODO: 경험치 막대가 필요 -->
    <div class="general-exp-level">
      {{ general.explevel }}
    </div>
    <div class="general-exp-level-bar d-grid">
      <div class="align-self-center">
        <SammoBar
          :height="10"
          :percent="(([a, b]) => (a / b) * 100)(nextExpLevelRemain(general.experience, general.explevel))"
        />
      </div>
    </div>
    <div class="bg1">연령</div>
    <div :style="{ color: ageColor }">{{ general.age }}세</div>

    <div class="bg1">수비</div>
    <div class="general-defence-train">
      <span v-if="general.defence_train === 999" style="color: red">수비 안함</span>
      <span v-else style="color: limegreen">수비 함(훈사{{ general.defence_train }})</span>
    </div>
    <div class="bg1">삭턴</div>
    <div>{{ general.killturn }} 턴</div>
    <div class="bg1">실행</div>
    <div>{{ nextExecuteMinute }}분 남음</div>

    <div class="bg1">부대</div>
    <div v-if="!troopInfo" class="general-troop">-</div>
    <div v-else class="general-troop">
      <s
        v-if="troopInfo.leader.reservedCommand && troopInfo.leader.reservedCommand[0].action != 'che_집합'"
        style="color: gray"
      >
        {{ troopInfo.name }}
      </s>
      <span v-else-if="troopInfo.leader.city == general.city">{{ troopInfo.name }}</span>
      <span v-else style="color: orange">
        {{ troopInfo.name }}({{ formatCityName(troopInfo.leader, gameConstStore) }})
      </span>
    </div>
    <div class="bg1">벌점</div>
    <div class="general-refresh-score-total">
      {{ formatRefreshScore(general.refreshScoreTotal) }} {{ (general.refreshScoreTotal ?? 0).toLocaleString() }}점({{
        general.refreshScore ?? 0
      }})
    </div>
  </div>
</template>

<script lang="ts" setup>
import type { GeneralListItemP1 } from "@/defs/API/Nation";
import { inject, ref, toRefs, watch, type Ref } from "vue";
import { getIconPath } from "@/util/getIconPath";
import { isBrightColor } from "@/util/isBrightColor";
import { formatInjury } from "@/utilGame/formatInjury";
import type { NationStaticItem } from "@/defs";
import { unwrap } from "@/util/unwrap";
import type { GameConstStore } from "@/GameConstStore";
import { formatGeneralTypeCall } from "@/utilGame/formatGeneralTypeCall";
import { nextExpLevelRemain } from "@/utilGame/nextExpLevelRemain";
import { formatRefreshScore } from "@/utilGame/formatRefreshScore";
import SammoBar from "@/components/SammoBar.vue";
import { parseTime } from "@/util/parseTime";
import { clamp } from "lodash-es";
import { formatCityName } from "@/utilGame/formatCityName";
import { isValidObjKey } from "@/utilGame/isValidObjKey";
import { calcInjury } from "@/utilGame/calcInjury";
import { addMinutes } from "date-fns/esm";
import type { GameIActionInfo } from "@/defs/GameObj";
const imagePath = window.pathConfig.gameImage;
const gameConstStore = unwrap(inject<Ref<GameConstStore>>("gameConstStore"));
const props = defineProps<{
  general: GeneralListItemP1;
  troopInfo?: {
    leader: {
      city: number;
      reservedCommand?: GeneralListItemP1["reservedCommand"];
    };
    name: string;
  };
  nation: NationStaticItem;
  turnTerm: number;
  lastExecuted: Date;
}>();

const { general, troopInfo, nation } = toRefs(props);
const iconPath = ref("");

const injuryInfo = ref<{ text: string; color: string }>({ text: "-", color: "white" });
const generalTypeCall = ref<string>("-");

const ageColor = ref<string>("limegreen");

const statUpThreshold = gameConstStore.value.gameConst.upgradeLimit;

watch(
  general,
  (general) => {
    iconPath.value = getIconPath(general.imgsvr, general.picture);

    const [text, color] = formatInjury(general.injury);
    injuryInfo.value = { text, color };

    generalTypeCall.value = formatGeneralTypeCall(
      general.leadership,
      general.strength,
      general.intel,
      gameConstStore.value.gameConst,
    );

    ageColor.value = (() => {
      const age = general.age;
      const retirementYear = gameConstStore.value.gameConst.retirementYear;
      if (age < retirementYear * 0.75) {
        return "limegreen";
      }
      if (age < retirementYear) {
        return "yellow";
      }
      return "red";
    })();
  },
  { immediate: true },
);

const dummyInfo: GameIActionInfo = { value: "None", name: "-", info: "" };

const horse = ref<GameIActionInfo>(dummyInfo);
const weapon = ref<GameIActionInfo>(dummyInfo);
const book = ref<GameIActionInfo>(dummyInfo);
const item = ref<GameIActionInfo>(dummyInfo);

const crewtype = ref<GameIActionInfo>(dummyInfo);

const personal = ref<GameIActionInfo>(dummyInfo);
const specialDomestic = ref<GameIActionInfo>(dummyInfo);
const specialWar = ref<GameIActionInfo>(dummyInfo);

watch(
  general,
  (general) => {
    horse.value = !isValidObjKey(general.horse) ? dummyInfo : gameConstStore.value.iActionInfo.item[general.horse];
    weapon.value = !isValidObjKey(general.weapon) ? dummyInfo : gameConstStore.value.iActionInfo.item[general.weapon];
    book.value = !isValidObjKey(general.book) ? dummyInfo : gameConstStore.value.iActionInfo.item[general.book];
    item.value = !isValidObjKey(general.item) ? dummyInfo : gameConstStore.value.iActionInfo.item[general.item];

    crewtype.value = !isValidObjKey(general.crewtype)
      ? dummyInfo
      : gameConstStore.value.iActionInfo.crewtype[general.crewtype];

    personal.value = !isValidObjKey(general.personal)
      ? dummyInfo
      : gameConstStore.value.iActionInfo.personality[general.personal];

    specialDomestic.value = !isValidObjKey(general.specialDomestic)
      ? { value: "None", name: `${Math.max(general.age + 1, general.specage)}세`, info: "-" }
      : gameConstStore.value.iActionInfo.specialDomestic[general.specialDomestic];
    specialWar.value = !isValidObjKey(general.specialWar)
      ? { value: "None", name: `${Math.max(general.age + 1, general.specage2)}세`, info: "-" }
      : gameConstStore.value.iActionInfo.specialWar[general.specialWar];
  },
  { immediate: true },
);

const nextExecuteMinute = ref(999);
watch(
  general,
  () => {
    let turnTime = parseTime(general.value.turntime);
    if (turnTime.getTime() < props.lastExecuted.getTime()) {
      turnTime = addMinutes(turnTime, props.turnTerm);
    }
    nextExecuteMinute.value = Math.floor(clamp((turnTime.getTime() - props.lastExecuted.getTime()) / 60000, 0, 999));
  },
  { immediate: true },
);
</script>

<style lang="scss" scoped>
.general-card-basic {
  display: grid;
  grid-template-columns: 64px repeat(3, 2fr 5fr);
  grid-template-rows: repeat(9, calc(64px / 3));
  text-align: center;
  font-size: 14px;

  border-bottom: 1px solid gray;
  border-right: 1px solid gray;

  > div.bg1,
  > .general-crew-type-icon,
  > .general-icon {
    border-left: 1px solid gray;
  }
  > div {
    border-top: 1px solid gray;
  }
}

.general-icon {
  width: 64px;
  height: 64px;
  background-size: contain;
  background-repeat: no-repeat;
  grid-row: 1 / 4;
}

.general-name {
  grid-row: 1 / 2;
  grid-column: 2 / 8;
  font-weight: bold;
}

.general-crew-type-icon {
  width: 64px;
  height: 64px;
  background-size: contain;
  background-repeat: no-repeat;
  grid-row: 4 / 7;
}

.general-exp-level-bar {
  grid-column: 3 / 6;
}

.general-defence-train {
  grid-column: 2 / 4;
}

.general-troop {
  grid-column: 2 / 4;
}

.general-refresh-score-total {
  grid-column: 5 / 8;
}
</style>

// apps/web/src/components/game/GeneralBasicCard.tsx
/**
 * GeneralBasicCard - General (장수) information card
 * Ported from legacy/hwe/ts/components/GeneralBasicCard.vue
 * Complex 350-line Vue component with grid layout
 */

import { SammoBar } from "./SammoBar";

/**
 * Determines if a color is bright (should use black text) or dark (should use white text)
 */
function isBrightColor(hexColor: string): boolean {
  const hex = hexColor.replace("#", "");
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);
  const brightness = (r * 299 + g * 587 + b * 114) / 1000;
  return brightness > 128;
}

/**
 * Format injury text and color
 */
function formatInjury(injury: number): [string, string] {
  if (injury === 0) return ["건강", "limegreen"];
  if (injury <= 20) return ["경상", "yellow"];
  if (injury <= 50) return ["중상", "orange"];
  if (injury <= 80) return ["위독", "orangered"];
  return ["빈사", "red"];
}

/**
 * Calculate stat with injury penalty
 */
function calcInjury(statName: "leadership" | "strength" | "intel", general: GeneralData): number {
  const baseStat = general[statName];
  const injuryPenalty = Math.floor(baseStat * (general.injury / 200));
  return baseStat - injuryPenalty;
}

/**
 * Format general type call based on stats
 */
function formatGeneralTypeCall(
  leadership: number,
  strength: number,
  intel: number,
  gameConst: GameConst
): string {
  const threshold = gameConst.chipiLimit ?? 60;
  const isHighLeadership = leadership >= threshold;
  const isHighStrength = strength >= threshold;
  const isHighIntel = intel >= threshold;

  const count = [isHighLeadership, isHighStrength, isHighIntel].filter(Boolean).length;

  if (count === 3) return "만능";
  if (count === 2) {
    if (!isHighLeadership) return "무지";
    if (!isHighStrength) return "지장";
    if (!isHighIntel) return "용장";
  }
  if (count === 1) {
    if (isHighLeadership) return "통장";
    if (isHighStrength) return "무장";
    if (isHighIntel) return "책사";
  }
  return "졸장";
}

/**
 * Format city name (태수 도시 표시용)
 */
function formatCityName(
  target: { city?: number } | number,
  gameConstStore: GameConstStore
): string {
  const cityId = typeof target === "number" ? target : target.city;
  if (!cityId) return "";
  const city = gameConstStore.cityConst[cityId];
  return city?.name ?? `도시${cityId}`;
}

/**
 * Calculate remaining exp to next level
 */
function nextExpLevelRemain(experience: number, explevel: number): [number, number] {
  // Simplified calculation - actual formula may differ
  const expPerLevel = 1000;
  const currentLevelExp = explevel * expPerLevel;
  const nextLevelExp = (explevel + 1) * expPerLevel;
  const currentProgress = experience - currentLevelExp;
  const required = nextLevelExp - currentLevelExp;
  return [Math.max(0, currentProgress), required];
}

/**
 * Format refresh score display
 */
function formatRefreshScore(score: number | undefined): string {
  if (!score) return "";
  if (score >= 10000) return "위험";
  if (score >= 5000) return "경고";
  if (score >= 1000) return "주의";
  return "";
}

// Type definitions
interface GameIActionInfo {
  value: string;
  name: string;
  info: string;
}

interface ReservedCommand {
  action: string;
}

interface GeneralData {
  name: string;
  imgsvr: number;
  picture: string;
  officerLevel: number;
  officerLevelText: string;
  officer_city?: number;
  turntime: string;
  leadership: number;
  strength: number;
  intel: number;
  leadership_exp: number;
  strength_exp: number;
  intel_exp: number;
  lbonus: number;
  injury: number;
  horse: string;
  weapon: string;
  book: string;
  item: string;
  gold: number;
  rice: number;
  crewtype: number;
  crew: number;
  personal: string;
  train: number;
  atmos: number;
  specialDomestic: string;
  specialWar: string;
  age: number;
  specage: number;
  specage2: number;
  explevel: number;
  experience: number;
  defence_train: number;
  killturn: number;
  city: number;
  refreshScore?: number;
  refreshScoreTotal?: number;
  reservedCommand?: ReservedCommand[];
}

interface TroopInfo {
  leader: {
    city: number;
    reservedCommand?: ReservedCommand[];
  };
  name: string;
}

interface NationStaticItem {
  color: string;
}

interface GameConst {
  upgradeLimit: number;
  retirementYear: number;
  chipiLimit?: number;
}

interface GameConstStore {
  gameConst: GameConst;
  cityConst: Record<number, { name: string }>;
  iActionInfo: {
    item: Record<string, GameIActionInfo>;
    crewtype: Record<number, GameIActionInfo>;
    personality: Record<string, GameIActionInfo>;
    specialDomestic: Record<string, GameIActionInfo>;
    specialWar: Record<string, GameIActionInfo>;
  };
}

interface GeneralBasicCardProps {
  general: GeneralData;
  troopInfo?: TroopInfo;
  nation: NationStaticItem;
  turnTerm: number;
  lastExecuted: Date;
  gameConstStore: GameConstStore;
  imagePath?: string;
}

const dummyInfo: GameIActionInfo = { value: "None", name: "-", info: "" };

export function GeneralBasicCard({
  general,
  troopInfo,
  nation,
  turnTerm,
  lastExecuted,
  gameConstStore,
  imagePath,
}: GeneralBasicCardProps) {
  const { gameConst, iActionInfo } = gameConstStore;
  const statUpThreshold = gameConst.upgradeLimit;

  // Get icon path
  const iconPath = general.picture
    ? `${imagePath}/general/${general.imgsvr}/${general.picture}`
    : `${imagePath}/general/default.png`;

  // Injury info
  const [injuryText, injuryColor] = formatInjury(general.injury);

  // General type call
  const generalTypeCall = formatGeneralTypeCall(
    general.leadership,
    general.strength,
    general.intel,
    gameConst
  );

  // Age color
  const retirementYear = gameConst.retirementYear;
  let ageColor = "limegreen";
  if (general.age >= retirementYear) {
    ageColor = "red";
  } else if (general.age >= retirementYear * 0.75) {
    ageColor = "yellow";
  }

  // Items
  const isValidObjKey = (key: string | number): boolean => key !== "None" && key !== "";
  const horse = isValidObjKey(general.horse) ? iActionInfo.item[general.horse] : dummyInfo;
  const weapon = isValidObjKey(general.weapon) ? iActionInfo.item[general.weapon] : dummyInfo;
  const book = isValidObjKey(general.book) ? iActionInfo.item[general.book] : dummyInfo;
  const item = isValidObjKey(general.item) ? iActionInfo.item[general.item] : dummyInfo;
  const crewtype = iActionInfo.crewtype[general.crewtype] ?? dummyInfo;
  const personal = isValidObjKey(general.personal)
    ? iActionInfo.personality[general.personal]
    : dummyInfo;

  // Special abilities
  const specialDomestic = isValidObjKey(general.specialDomestic)
    ? iActionInfo.specialDomestic[general.specialDomestic]
    : { value: "None", name: `${Math.max(general.age + 1, general.specage)}세`, info: "-" };
  const specialWar = isValidObjKey(general.specialWar)
    ? iActionInfo.specialWar[general.specialWar]
    : { value: "None", name: `${Math.max(general.age + 1, general.specage2)}세`, info: "-" };

  // Calculate next execute minute
  const parseTime = (timeStr: string): Date => new Date(timeStr);
  let turnTime = parseTime(general.turntime);
  if (turnTime.getTime() < lastExecuted.getTime()) {
    turnTime = new Date(turnTime.getTime() + turnTerm * 60000);
  }
  const nextExecuteMinute = Math.floor(
    Math.max(0, Math.min(999, (turnTime.getTime() - lastExecuted.getTime()) / 60000))
  );

  // Exp level progress
  const [expProgress, expRequired] = nextExpLevelRemain(general.experience, general.explevel);

  // Name color
  const nameColor = isBrightColor(nation.color) ? "#000" : "#fff";

  return (
    <div className="general-card-basic bg2">
      <style jsx>{`
        .general-card-basic {
          display: grid;
          grid-template-columns: 64px repeat(3, 2fr 5fr);
          grid-template-rows: repeat(9, calc(64px / 3));
          text-align: center;
          font-size: 14px;
          border-bottom: 1px solid gray;
          border-right: 1px solid gray;
        }

        .general-card-basic > div.bg1,
        .general-card-basic > .general-crew-type-icon,
        .general-card-basic > .general-icon {
          border-left: 1px solid gray;
        }

        .general-card-basic > div {
          border-top: 1px solid gray;
        }

        .general-icon {
          width: 64px;
          height: 64px;
          background-size: contain;
          background-repeat: no-repeat;
          grid-row: 1 / 4;
        }

        .general-name {
          grid-row: 1 / 2;
          grid-column: 2 / 8;
          font-weight: bold;
        }

        .general-crew-type-icon {
          width: 64px;
          height: 64px;
          background-size: contain;
          background-repeat: no-repeat;
          grid-row: 4 / 7;
        }

        .general-exp-level-bar {
          grid-column: 3 / 6;
        }

        .general-defence-train {
          grid-column: 2 / 4;
        }

        .general-troop {
          grid-column: 2 / 4;
        }

        .general-refresh-score-total {
          grid-column: 5 / 8;
        }

        .row {
          display: flex;
          gap: 0;
        }

        .col {
          flex: 1;
        }

        .align-self-center {
          align-self: center;
        }

        .d-grid {
          display: grid;
        }
      `}</style>

      {/* General Icon */}
      <div className="general-icon" style={{ backgroundImage: `url('${iconPath}')` }} />

      {/* General Name */}
      <div
        className="general-name"
        style={{
          color: nameColor,
          backgroundColor: nation.color,
        }}
      >
        {general.name} 【
        {general.officerLevel >= 2 && general.officerLevel <= 4 && general.officer_city && (
          <>{formatCityName(general.officer_city, gameConstStore)}</>
        )}
        {general.officerLevelText} | {generalTypeCall} |{" "}
        <span style={{ color: injuryColor }}>{injuryText}</span>】{" "}
        {general.turntime.substring(11, 19)}
      </div>

      {/* Leadership */}
      <div className="bg1">통솔</div>
      <div>
        <div className="row">
          <div className="col">
            <span style={{ color: injuryColor }}>{calcInjury("leadership", general)}</span>
            {general.lbonus > 0 && <span style={{ color: "cyan" }}>+{general.lbonus}</span>}
          </div>
          <div className="col align-self-center">
            <SammoBar height={10} percent={(general.leadership_exp / statUpThreshold) * 100} />
          </div>
        </div>
      </div>

      {/* Strength */}
      <div className="bg1">무력</div>
      <div>
        <div className="row">
          <div className="col" style={{ color: injuryColor }}>
            {calcInjury("strength", general)}
          </div>
          <div className="col align-self-center">
            <SammoBar height={10} percent={(general.strength_exp / statUpThreshold) * 100} />
          </div>
        </div>
      </div>

      {/* Intel */}
      <div className="bg1">지력</div>
      <div>
        <div className="row">
          <div className="col" style={{ color: injuryColor }}>
            {calcInjury("intel", general)}
          </div>
          <div className="col align-self-center">
            <SammoBar height={10} percent={(general.intel_exp / statUpThreshold) * 100} />
          </div>
        </div>
      </div>

      {/* Horse */}
      <div className="bg1">명마</div>
      <div title={horse.info || undefined}>{horse.name}</div>

      {/* Weapon */}
      <div className="bg1">무기</div>
      <div title={weapon.info || undefined}>{weapon.name}</div>

      {/* Book */}
      <div className="bg1">서적</div>
      <div title={book.info || undefined}>{book.name}</div>

      {/* Gold */}
      <div className="bg1">자금</div>
      <div>{general.gold.toLocaleString()}</div>

      {/* Rice */}
      <div className="bg1">군량</div>
      <div>{general.rice.toLocaleString()}</div>

      {/* Item */}
      <div className="bg1">도구</div>
      <div title={item.info || undefined}>{item.name}</div>

      {/* Crew Type Icon */}
      <div
        className="general-crew-type-icon"
        style={{
          backgroundImage: `url('${imagePath}/crewtype${general.crewtype}.png')`,
        }}
      />

      {/* Crew Type */}
      <div className="bg1">병종</div>
      <div title={crewtype.info || undefined}>{crewtype.name}</div>

      {/* Crew */}
      <div className="bg1">병사</div>
      <div>{general.crew.toLocaleString()}</div>

      {/* Personality */}
      <div className="bg1">성격</div>
      <div title={personal.info || undefined}>{personal.name}</div>

      {/* Train */}
      <div className="bg1">훈련</div>
      <div>{general.train}</div>

      {/* Atmos */}
      <div className="bg1">사기</div>
      <div>{general.atmos}</div>

      {/* Specials */}
      <div className="bg1">특기</div>
      <div>
        <span title={specialDomestic.info || undefined}> {specialDomestic.name}</span>
        {" / "}
        <span title={specialWar.info || undefined}> {specialWar.name}</span>
      </div>

      {/* Level */}
      <div className="bg1">Lv</div>
      <div className="general-exp-level">{general.explevel}</div>
      <div className="general-exp-level-bar d-grid">
        <div className="align-self-center">
          <SammoBar height={10} percent={(expProgress / expRequired) * 100} />
        </div>
      </div>

      {/* Age */}
      <div className="bg1">연령</div>
      <div style={{ color: ageColor }}>{general.age}세</div>

      {/* Defence */}
      <div className="bg1">수비</div>
      <div className="general-defence-train">
        {general.defence_train === 999 ? (
          <span style={{ color: "red" }}>수비 안함</span>
        ) : (
          <span style={{ color: "limegreen" }}>수비 함(훈사{general.defence_train})</span>
        )}
      </div>

      {/* Kill Turn */}
      <div className="bg1">삭턴</div>
      <div>{general.killturn} 턴</div>

      {/* Execute */}
      <div className="bg1">실행</div>
      <div>{nextExecuteMinute}분 남음</div>

      {/* Troop */}
      <div className="bg1">부대</div>
      <div className="general-troop">
        {!troopInfo ? (
          "-"
        ) : troopInfo.leader.reservedCommand &&
          troopInfo.leader.reservedCommand[0]?.action !== "che_집합" ? (
          <s style={{ color: "gray" }}>{troopInfo.name}</s>
        ) : troopInfo.leader.city === general.city ? (
          <span>{troopInfo.name}</span>
        ) : (
          <span style={{ color: "orange" }}>
            {troopInfo.name}({formatCityName(troopInfo.leader, gameConstStore)})
          </span>
        )}
      </div>

      {/* Refresh Score */}
      <div className="bg1">벌점</div>
      <div className="general-refresh-score-total">
        {formatRefreshScore(general.refreshScoreTotal)}{" "}
        {(general.refreshScoreTotal ?? 0).toLocaleString()}점(
        {general.refreshScore ?? 0})
      </div>
    </div>
  );
}
