// legacy/hwe/ts/components/MapCityBasic.vue
<template>
  <div
    :class="['city_base', `city_base_${city.id}`, `city_level_${city.level}`]"
    :style="cityPos"
    @mouseenter="silent"
    @mouseleave="silent"
  >
    <a
      class="city_link"
      :data-text="city.text"
      :data-nation="city.nation"
      :data-id="city.id"
      :href="props.href"
      :style="{
        cursor: city.clickable ? 'pointer' : 'default',
      }"
      @click="clicked"
      @touchstart="touchstart"
      @touchmove="touchmove"
      @touchend="touchend"
      @mouseenter="mouseenter"
      @mouseleave="mouseleave"
    >
      <div
        class="city_img"
        :style="{
          backgroundColor: city.color,
        }"
      >
        <div :class="['city_filler', props.isMyCity ? 'my_city' : '']"></div>
        <div v-if="city.state > 0" :class="['city_state', `city_state_${getCityState()}`]"></div>
        <div v-if="city.nationID && city.nationID > 0" class="city_flag">
          <div v-if="city.isCapital" class="city_capital"></div>
        </div>
        <span class="city_detail_name">{{ city.name }}</span>
      </div>
    </a>
  </div>
</template>

<script lang="ts" setup>
import type { MapCityParsed } from "@/map";
import { ref, toRef, watch, type PropType } from "vue";
const emit = defineEmits<{
  (event: "click", evnet: MouseEvent | TouchEvent): void;
  (event: "mouseenter", e: MouseEvent): void;
  (event: "mouseleave", e: MouseEvent): void;
  (event: "touchleave", e: TouchEvent): void;
}>();
const props = defineProps({
  city: {
    type: Object as PropType<MapCityParsed>,
    required: true,
  },
  href: {
    type: String,
    default: undefined,
    required: false,
  },
  isMyCity: {
    type: Boolean,
    required: false,
    defeault: false,
  },
  isFullWidth: {
    type: Boolean,
    required: true,
  },
});

const city = toRef(props, "city");
const cityPos = ref({
  left: "0px",
  top: "0px",
});
watch(
  () => props.isFullWidth,
  (isFullWidth) => {
    const { x, y } = city.value;
    if (isFullWidth) {
      cityPos.value = {
        left: `${x - 20}px`,
        top: `${y - 15}px`,
      };
    } else {
      cityPos.value = {
        left: `${(x * 5) / 7 - 20}px`,
        top: `${(y * 5) / 7 - 18}px`,
      };
    }
  },
  { immediate: true },
);
function getCityState(): string {
  const state = city.value.state;
  if (state < 10) {
    return "good";
  }
  if (state < 40) {
    return "bad";
  }
  if (state < 50) {
    return "war";
  }
  return "wrong";
}

function clicked(event: MouseEvent) {
  emit("click", event);
}

function mouseenter(event: MouseEvent) {
  event.stopPropagation();
  emit("mouseenter", event);
}

function mouseleave(event: MouseEvent) {
  event.stopPropagation();
  emit("mouseleave", event);
}

let touchOnTrack = false;

function touchstart() {
  touchOnTrack = true;
}

function touchmove() {
  touchOnTrack = false;
}

function touchend(event: TouchEvent) {
  if (touchOnTrack) {
    event.stopPropagation();
    emit("click", event);
  } else {
    emit("touchleave", event);
  }
}
function silent(event: MouseEvent) {
  event.stopPropagation();
}
</script>

<style lang="scss" scoped>
a,
div,
span {
  line-height: 1.3;
  font-size: 14px;
}
</style>

// apps/web/src/components/game/MapCityBasic.tsx
"use client";

import React, { useRef, useMemo, useCallback } from "react";

// ============================================================================
// Types
// ============================================================================

export interface MapCityParsed {
  id: number;
  name: string;
  x: number;
  y: number;
  level: number;
  state: number;
  nationID?: number;
  nation?: string;
  color?: string;
  region: number;
  region_str: string;
  level_str: string;
  text: string;
  supply: boolean;
  isCapital: boolean;
  clickable: number;
}

interface MapCityBasicProps {
  city: MapCityParsed;
  href?: string;
  isMyCity?: boolean;
  isFullWidth: boolean;
  onClick?: (e: React.MouseEvent | React.TouchEvent) => void;
  onMouseEnter?: (e: React.MouseEvent) => void;
  onMouseLeave?: (e: React.MouseEvent) => void;
  onTouchLeave?: (e: React.TouchEvent) => void;
}

// ============================================================================
// Helper Functions
// ============================================================================

function getCityState(state: number): string {
  if (state < 10) return "good";
  if (state < 40) return "bad";
  if (state < 50) return "war";
  return "wrong";
}

// ============================================================================
// Component
// ============================================================================

export function MapCityBasic({
  city,
  href,
  isMyCity = false,
  isFullWidth,
  onClick,
  onMouseEnter,
  onMouseLeave,
  onTouchLeave,
}: MapCityBasicProps) {
  const touchOnTrackRef = useRef(false);

  // Calculate position based on width mode
  const cityPos = useMemo(() => {
    const { x, y } = city;
    if (isFullWidth) {
      return {
        left: `${x - 20}px`,
        top: `${y - 15}px`,
      };
    }
    return {
      left: `${(x * 5) / 7 - 20}px`,
      top: `${(y * 5) / 7 - 18}px`,
    };
  }, [city.x, city.y, isFullWidth]);

  const handleClick = useCallback(
    (e: React.MouseEvent) => {
      onClick?.(e);
    },
    [onClick]
  );

  const handleMouseEnter = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      onMouseEnter?.(e);
    },
    [onMouseEnter]
  );

  const handleMouseLeave = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      onMouseLeave?.(e);
    },
    [onMouseLeave]
  );

  const handleTouchStart = useCallback(() => {
    touchOnTrackRef.current = true;
  }, []);

  const handleTouchMove = useCallback(() => {
    touchOnTrackRef.current = false;
  }, []);

  const handleTouchEnd = useCallback(
    (e: React.TouchEvent) => {
      if (touchOnTrackRef.current) {
        e.stopPropagation();
        onClick?.(e);
      } else {
        onTouchLeave?.(e);
      }
    },
    [onClick, onTouchLeave]
  );

  const handleSilent = useCallback((e: React.MouseEvent) => {
    e.stopPropagation();
  }, []);

  const LinkOrDiv = href ? "a" : "div";

  return (
    <div
      className={`city_base city_base_${city.id} city_level_${city.level}`}
      style={cityPos}
      onMouseEnter={handleSilent}
      onMouseLeave={handleSilent}
    >
      <LinkOrDiv
        className="city_link"
        data-text={city.text}
        data-nation={city.nation}
        data-id={city.id}
        {...(href ? { href } : {})}
        style={{
          cursor: city.clickable ? "pointer" : "default",
        }}
        onClick={handleClick}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <div
          className="city_img"
          style={{
            backgroundColor: city.color || "#ffffff",
          }}
        >
          <div className={`city_filler ${isMyCity ? "my_city" : ""}`} />
          {city.state > 0 && (
            <div className={`city_state city_state_${getCityState(city.state)}`} />
          )}
          {city.nationID && city.nationID > 0 && (
            <div className="city_flag">{city.isCapital && <div className="city_capital" />}</div>
          )}
          <span className="city_detail_name">{city.name}</span>
        </div>
      </LinkOrDiv>
    </div>
  );
}
